force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <description>Members or employees of the guild</description>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Member_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Guild Hall Administrator</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guild_Member__c/fields/Levels__c.field-meta.xml
<CustomField>
    <fullName>Levels__c</fullName>
    <description>Total levels of an adventurer&apos;s classes</description>
    <label>Levels</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guild_Member__c/recordTypes/Adventurer.recordType-meta.xml
<RecordType>
    <fullName>Adventurer</fullName>
    <active>true</active>
    <description>Guild member who handles quests</description>
    <label>Adventurer</label>
</RecordType>

force-app/main/default/classes/GuildMemberTriggerHandler.cls
/* Name: P0 Guild Member Object Trigger Handler
 * Author: Blake Prescott(blake.prescott@revature.net)
 * Created Date: 7/16/21 
 * Last Modified Date: 7/18/21
 * Description: This is the handler for the Guild Member trigger.
 */
public class GuildMemberTriggerHandler {
    public static void maxMinMemberLevels(List<Guild_Member__c> gm){
        for (Guild_Member__c g : gm) {           
            If(g.RecordTypeId == '0125e0000006hYm') {
                Integer minLevels = g.class__c.countMatches(';')+1;
                system.debug(minLevels);
                system.debug(g.class__c);
                If(g.Levels__c < minLevels || g.Levels__c > 20){
                    g.addError('An adventurer cannot have fewer levels than classes and cannot have more than 20 levels.');
                }
            }    
        }
    }
}