force-app/main/default/objects/Guild_Member__c/Guild_Member__c.object-meta.xml
<CustomObject>
    <description>Members or employees of the guild</description>
    <label>Guild Member</label>
    <nameField>
        <label>Guild Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Members</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Guild_Member__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Member_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Artificer</fullName>
            </value>
            <value>
                <fullName>Barbarian</fullName>
            </value>
            <value>
                <fullName>Bard</fullName>
            </value>
            <value>
                <fullName>Cleric</fullName>
            </value>
            <value>
                <fullName>Druid</fullName>
            </value>
            <value>
                <fullName>Fighter</fullName>
            </value>
            <value>
                <fullName>Guild Hall Administrator</fullName>
            </value>
            <value>
                <fullName>Monk</fullName>
            </value>
            <value>
                <fullName>Paladin</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
            <value>
                <fullName>Rogue</fullName>
            </value>
            <value>
                <fullName>Sorcerer</fullName>
            </value>
            <value>
                <fullName>Warlock</fullName>
            </value>
            <value>
                <fullName>Wizard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guild_Member__c/fields/Levels__c.field-meta.xml
<CustomField>
    <fullName>Levels__c</fullName>
    <description>Total levels of an adventurer&apos;s classes</description>
    <label>Levels</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Guild_Member__c/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <label>Member Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guild_Member__c/recordTypes/Adventurer.recordType-meta.xml
<RecordType>
    <fullName>Adventurer</fullName>
    <active>true</active>
    <description>Guild member who handles quests</description>
    <label>Adventurer</label>
</RecordType>

force-app/main/default/objects/Guild_Member__c/recordTypes/Expert.recordType-meta.xml
<RecordType>
    <fullName>Expert</fullName>
    <active>true</active>
    <description>Guild member who handles requests for expertise</description>
    <label>Expert</label>
</RecordType>

force-app/main/default/classes/GuildMemberTriggerTest.cls
/* Name: P0 Guild Member Object Trigger Handler Tests
 * Author: Blake Prescott(blake.prescott@revature.net)
 * Created Date: 7/16/21 
 * Last Modified Date: 7/18/21
 * Description: This is the test class for the guild member trigger. I did tests for success and failure but bulk tests in this particular case don't
 * make a lot of sense to me since nothing in the triggers interacts with anything outside of the record.
 */
@isTest
public class GuildMemberTriggerTest {
	
    @isTest
    public static void singleMinFailTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 1);
        database.SaveResult sr = database.insert(testGM, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        }        
        system.assertEquals(1, numFailed);
    }
    
    @isTest
    public static void singleMinSuccessTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 2);
        database.SaveResult sr = database.insert(testGM, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        }
		        
        system.assertEquals(0, numFailed);
    }
    
    @isTest
    public static void singleMaxFailTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 21);
        database.SaveResult sr = database.insert(testGM, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        }        
        system.assertEquals(1, numFailed);
    }
    
    @isTest
    public static void singleMaxSuccessTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 20);
        database.SaveResult sr = database.insert(testGM, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        }        
        system.assertEquals(0, numFailed);
    }
    
    @isTest
    public static void singleMinUpdateFailTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 2);
        insert testGM;
        Guild_Member__c gm = [SELECT levels__c, class__c FROM Guild_Member__c LIMIT 1];
        gm.Levels__c = 1;
        database.SaveResult sr = database.update(gm, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        } 
        system.assertEquals(1, numFailed);
    }
    
    @isTest
    public static void singleMinUpdateSuccessTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYm', Member_Type__c = 'Adventurer', Class__c = 'Bard;Sorcerer', levels__c = 2);
        insert testGM;
        Guild_Member__c gm = [SELECT levels__c, class__c FROM Guild_Member__c LIMIT 1];
        gm.Levels__c = 3;
        database.SaveResult sr = database.update(gm, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        } 
        system.assertEquals(0, numFailed);
    }
    
    @isTest
    public static void ignoreExpertsTest(){
        Guild_Member__c testGM = new Guild_Member__c(name = 'testName', RecordTypeId = '0125e0000006hYr', Member_Type__c = 'Expert');
        database.SaveResult sr = database.insert(testGM, false);
        integer numFailed = 0;
        if(!sr.isSuccess()){
            numFailed = 1;
        } 
        system.assertEquals(0, numFailed);
    }
}